// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mitie_load_ner_model
SEXP mitie_load_ner_model(std::string model_path);
RcppExport SEXP _rmitie_mitie_load_ner_model(SEXP model_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model_path(model_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(mitie_load_ner_model(model_path));
    return rcpp_result_gen;
END_RCPP
}
// mitie_tokenize
List mitie_tokenize(std::string text);
RcppExport SEXP _rmitie_mitie_tokenize(SEXP textSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type text(textSEXP);
    rcpp_result_gen = Rcpp::wrap(mitie_tokenize(text));
    return rcpp_result_gen;
END_RCPP
}
// mitie_extract_entities
DataFrame mitie_extract_entities(SEXP model_xptr, CharacterVector tokens_r);
RcppExport SEXP _rmitie_mitie_extract_entities(SEXP model_xptrSEXP, SEXP tokens_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_xptr(model_xptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tokens_r(tokens_rSEXP);
    rcpp_result_gen = Rcpp::wrap(mitie_extract_entities(model_xptr, tokens_r));
    return rcpp_result_gen;
END_RCPP
}
// mitie_ner_tags
CharacterVector mitie_ner_tags(SEXP model_xptr);
RcppExport SEXP _rmitie_mitie_ner_tags(SEXP model_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_xptr(model_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(mitie_ner_tags(model_xptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmitie_mitie_load_ner_model", (DL_FUNC) &_rmitie_mitie_load_ner_model, 1},
    {"_rmitie_mitie_tokenize", (DL_FUNC) &_rmitie_mitie_tokenize, 1},
    {"_rmitie_mitie_extract_entities", (DL_FUNC) &_rmitie_mitie_extract_entities, 2},
    {"_rmitie_mitie_ner_tags", (DL_FUNC) &_rmitie_mitie_ner_tags, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmitie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
