# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mitie_load_ner_model <- function(model_path) {
    .Call(`_rmitie_mitie_load_ner_model`, model_path)
}

mitie_tokenize <- function(text) {
    .Call(`_rmitie_mitie_tokenize`, text)
}

mitie_extract_entities <- function(model_xptr, tokens_r) {
    .Call(`_rmitie_mitie_extract_entities`, model_xptr, tokens_r)
}

mitie_ner_tags <- function(model_xptr) {
    .Call(`_rmitie_mitie_ner_tags`, model_xptr)
}

